### ISSUE TITLE
Homomorphic encryption support using TenSEAL

### ISSUE THREAD

**Issue by panoskyriakis** [bioint/MetisFL#46]
### 🚀 The feature

We are looking to implement a pure-python secure aggregation with homomorphic encryption using the [TenSEAL](https://github.com/OpenMined/TenSEAL) library. A helper function to easily generate the encryption keys could also be useful, please look at the `metisfl/helpers` for more info. 

### Motivation

Currently, MetisFL supports secure aggregation using the C++ implementation of the [Palisade](https://gitlab.com/palisade/palisade-release) library, which is being deprecated. Migrating to a pure python lib like TenSEAL will make it easier and faster to build. 

The current implementation (in C++) can be found [here](https://github.com/NevronAI/MetisFL/blob/devcpp/metisfl/encryption/palisade/ckks_scheme.cc) and could be a good starting point. Also, please have a  look [here](https://github.com/NevronAI/MetisFL/blob/devcpp/metisfl/controller/aggregation/secure_aggregation.cc).

**Comment by yashmaurya01** [comment]
I'm interested in working on this feature. 
If anyone else is keen to collaborate, please ping me on the Nevron.AI Slack to discuss.

Thanks!

**Comment by BhushanMahajan25** [comment]
@yashmaurya01 Hey! Yash. I am also thinking of working on this feature. Let's collaborate. I have pinged you on the Slack channel.
